# Generated by Django 3.0.7 on 2020-06-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
    ]
